### ISSUE TITLE
增加对stylus校验支持

### ISSUE THREAD

**Issue by chenEdgar** [levy9527/nuxt-element-dashboard#1]
复现：
1. git clone https://github.com/levy9527/nuxt-element-dashboard.git
2. yarn // 安装依赖
3. 随意修改 src/layouts/default.vue 的代码
4. git add . && git commit -m 'test'
5. 能够看到报错信息了

看起来是stylelint 对 stylus的校验支持不够

**Comment by levy9527** [comment]
[release 1.0.0 解决](https://github.com/levy9527/nuxt-element-dashboard/releases/tag/v1.0.0)
