### ISSUE TITLE
遗留代码？

### ISSUE THREAD

**Issue by shoyuf** [levy9527/nuxt-element-dashboard#20]
https://github.com/levy9527/nuxt-element-dashboard/blob/10040a7d0f1c066481fd59f188f7780eeb4976ed/nuxt.config.js#L75

该处的 process.client 在 dev 或 build 环境中都为 undefined，eslint 在代码中也未作用，是否为不需要的代码？

**Comment by levy9527** [comment]
@shoyuf 感谢指出。

**Comment by lianghx-319** [comment]
[https://nuxtjs.org/guide/development-tools#eslint-and-prettier](url)
![image](https://user-images.githubusercontent.com/27187946/59331586-e6163700-8d26-11e9-912f-39af4332f281.png)

应该是当初init的时候就有的，后面check一下过时配置

**Comment by levy9527** [comment]
这个其实是升级至nuxt2后遗漏的内容，不过也是有意不开启，因为启用eslint，会对团队编码习惯有影响。

正确的修改方案详见这个PR：https://github.com/FEMessage/create-nuxt-app/pull/43/files

建议是：如果要改正这里，最好与团队协商得出一份eslint规则后，再开启它。
