### ISSUE TITLE
meta 似乎有多余的信息

### ISSUE THREAD

**Issue by levy9527** [levy9527/nuxt-element-dashboard#21]
![image](https://user-images.githubusercontent.com/9384365/59254521-f06efd00-8c62-11e9-95e3-fd7e8bb34605.png)

这两个字段 似乎重复了

**Comment by lianghx-319** [comment]
这两个字段在模板中分别有不同作用，虽然暂时来看，两个字段的内容一样。

**Comment by levy9527** [comment]
分别是什么作用 要确定是不是多余的 现在不一定是对的

**Comment by levy9527** [comment]
已在  https://github.com/FEMessage/create-nuxt-app 解决
