### ISSUE TITLE
ExtractCSS will break CSS hot reload

### ISSUE THREAD

**Issue by shoyuf** [levy9527/nuxt-element-dashboard#24]
https://github.com/levy9527/nuxt-element-dashboard/blob/10040a7d0f1c066481fd59f188f7780eeb4976ed/nuxt.config.js#L59

如果在dev环境中设置extractCSS为true, 在组件中修改css属性将不会自动热更新，需要手动刷新才能看到效果

[relate link](https://github.com/nuxt/nuxt.js/issues/5390)

**Comment by levy9527** [comment]
收到！更新后会发布通知。这周在大面积清理组件的issue

**Comment by levy9527** [comment]
问题在这里解决了： https://github.com/FEMessage/create-nuxt-app/releases/tag/v1.3.0
